(** Surface sugar binds prelude constructors by identity (SX.31).

    [if], list literals, and [try] elaborate to matches on and constructions of the prelude's
    [Bool], [List], and [Result]. They name those constructors by identity, so a file that declares
    its own [True], [Cons], or [Ok] cannot capture the sugar: an explicitly written [True] still
    means the file's constructor, while [if] always means the prelude's [Bool]. *)

val constructors : (string * string) list
(** The store names and [HASH_V0] identities (hex) of [true], [false], [nil], [cons], [ok], and
    [err] as the prelude declares them. A test pins them against the loaded prelude. *)

val prelude_constructor : meta:Meta.t -> string -> Hash.t option
(** [prelude_constructor ~meta name] is the prelude identity a sugar-generated reference to [name]
    must mean, when [meta] marks the reference as generated by [if], a list literal, or [try];
    otherwise [None]. The resolver uses it only when the store actually holds that constructor, so
    environments without the prelude keep ordinary name resolution. *)
